export enum PRIVATE_ROUTES {
  CLIENT = "/client",
  CLIENT_CREATE = "/client/create",
  CLIENT_EDIT = "/client/edit/:id",
  DASHBOARD = "/dashboard",
  PROJECT = "/project",
  PROJECT_CREATE = "/project/create",
  PROJECT_EDIT_ID = "/project/edit/:id",
  PROJECT_EDIT = "/project/edit/",
  JOB_INFO = "/job-info",
  SEARCH_RESULTS = "/search-results",
  CANDIDATE_REVIEW = "/candidate-review",
  POSITION = "/position",
  POSITION_CREATE = "/position/create",
  POSITION_EDIT = "/position/edit/:id",
  PROFILE = "/profile",
  JOB_INFO_EDIT = "/job-info/edit",
  JOB_INFO_EDIT_ID = "/job-info/edit/:id",
}
