export type CandidateModel = {
  candidate_info_id: number;
  job_desc_id: number;
  full_name: string;
  linkedin_url: string;
  linkedin_username: string;
  linkedin_id: string;
  job_title: string;
  min_exp_start_date: number;
  max_exp_end_date: number;
  years_of_experience: number;
  skill_level_name: string;
  skill_level_id: number;
  user_base_info_id: number;
  overall_review: string;
  coding_standards: number;
  readability: number;
  modularity: number;
  error_handling: number;
  testing: number;
  documentation: number;
  active: boolean;
  InsertDate: number;
  ModifiedDate: number;
};
