export const persistedDataNameConstants = {
  USER_TK: "USER_TK",
  TOKEN_INIT_DATE: "TOKEN_INIT_DATE",
  USER_INFO: "USER_INFO",
  CLIENT_INFO: "CLIENT_INFO",
  PROJECT_INFO: "PROJECT_INFO",
  POSITION_INFO: "POSITION_INFO",
};
